name: parfume_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.2
  # Veri yönetimi ve arama motoru için gerekli paketler:
  sqflite: ^2.3.0
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  modbus: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/content/
    - assets/rules/
    - assets/fonts/ # Klasörü genel olarak eklemek de iyidir
    - assets/config/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf   
          weight: 700
    - family: Montserrat  # Yeni bir aile olarak tanımlıyoruz
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
